### ISSUE TITLE
The initial load of the UI returns a blank page

### ISSUE THREAD

**Issue by phriscage** [GoogleCloudPlatform/datashare-toolkit#139]
**Describe the bug**
The initial load of the UI returns a blank page. After refreshing it loads successfully. 

**Version**
[v0.3.0](https://github.com/GoogleCloudPlatform/datashare-toolkit/tree/v0.3.0)

**To Reproduce**

**Expected behavior**
The UI loads successfully on 1st render. 

**Screenshots**
```Uncaught FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values).
    at Nt (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1259:478)
    at At (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1259:251)
    at t.instanceFactory (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1275:148)
    at t.getOrInitializeService (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:16005)
    at t.getImmediate (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:14525)
    at t.instanceFactory (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1911:2633)
    at t.getOrInitializeService (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:16005)
    at t.getImmediate (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:746:14525)
    at t._getService (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1588:176118)
    at t.<computed> [as analytics] (https://cds-frontend-ui-74myzwomra-uc.a.run.app/js/chunk-vendors.680ed2bc.js:1604:1190)```
**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome Incognito


**Additional context**
Add any other context about the problem here.

**Comment by mservidio** [comment]
Uncaught FirebaseError: Installations: Missing App configuration value: "projectId" (installations/missing-app-config-values)
