### ISSUE TITLE
Unable to use gcpMetadata.isAvailable from GKE

### ISSUE THREAD

**Issue by mservidio** [GoogleCloudPlatform/datashare-toolkit#300]
Exception thrown when trying to get metadata from GKE.

`
const gcpMetadata = require('gcp-metadata');

const isAvailable = await gcpMetadata.isAvailable();
`

(node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
--
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1) UnhandledPromiseRejectionWarning: Error: 7 PERMISSION_DENIED: User not authorized to perform this action.     at Object.callErrorFromStatus (/shared/node_modules/@grpc/grpc-js/build/src/call.js:30:26)     at Object.onReceiveStatus (/shared/node_modules/@grpc/grpc-js/build/src/client.js:175:52)     at Object.onReceiveStatus (/shared/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:341:141)     at Object.onReceiveStatus (/shared/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:304:181)     at Http2CallStream.outputStatus (/shared/node_modules/@grpc/grpc-js/build/src/call-stream.js:116:74)     at Http2CallStream.maybeOutputStatus (/shared/node_modules/@grpc/grpc-js/build/src/call-stream.js:155:22)     at Http2CallStream.endCall (/shared/node_modules/@grpc/grpc-js/build/src/call-stream.js:141:18)     at Http2CallStream.handleTrailers (/shared/node_modules/@grpc/grpc-js/build/src/call-stream.js:273:14)     at ClientHttp2Stream.emit (events.js:203:13)     at emit (internal/http2/core.js:248:8)

https://github.com/googleapis/google-auth-library-nodejs/issues/798

**Comment by mservidio** [comment]
Granting compute.projects.get may have addressed this? Not seeing this issue anymore.
