### ISSUE TITLE
Error: Could not load the default credentials

### ISSUE THREAD

**Issue by mservidio** [GoogleCloudPlatform/datashare-toolkit#476]
Cloud run service logs constantly throwing:
```
Error
2021-04-09 20:30:14.732 EDTError: Could not load the default credentials. Browse to https://cloud.google.com/docs/authentication/getting-started for more information. at GoogleAuth.getApplicationDefaultAsync (/shared/node_modules/@google-cloud/bigquery/node_modules/google-auth-library/build/src/auth/googleauth.js:155:19) at processTicksAndRejections (internal/process/task_queues.js:85:5) at async GoogleAuth.getClient (/shared/node_modules/@google-cloud/bigquery/node_modules/google-auth-library/build/src/auth/googleauth.js:486:17) at async GoogleAuth.authorizeRequest (/shared/node_modules/@google-cloud/bigquery/node_modules/google-auth-library/build/src/auth/googleauth.js:527:24)
```

This started occurring in two separate environments over the past month.

**Comment by mservidio** [comment]
Fixed in documentation: https://github.com/GoogleCloudPlatform/datashare-toolkit/commit/c2ddcb385fd36d3e3de37728862d5700a6d35773
